### ISSUE TITLE
Add jumpstart packs to sealed simulator

### ISSUE THREAD

**Issue by axxroytovu** [taw/magic-search-engine#225]
> On May 1, 2023, at 08:32, Tuấn Dương Đức <[lokiplop908@gmail.com](mailto:lokiplop908@gmail.com)> wrote:
> Please put the jumpstar in to pack simulator web , thank youu :3

I got this email and figured I'd put it here. Specifically they want to open jumpstart packs in https://mtg.wtf/sealed

**Comment by axxroytovu** [comment]
> On May 1, 2023, at 8:51 AM, Tuấn Dương Đức <lokiplop908@gmail.com> wrote:
> Thank youu :3 , and you can put all the set secret liar into the sealed , is very okay to try it hehe

Also secret lair products I guess?

**Comment by Owensleepy** [comment]
> 

Yes, that right

**Comment by taw** [comment]
So for Jumpstart, it sort of makes sense, but it really does not fit the current system.

I'm not sure which Secret Lair subsets would work, aren't they mostly predetermined?

**Comment by taw** [comment]
Here's a draft how it might look like:

```
name: "Jumpstart"
pack:
- infantry_1: 19
  white_rare_mythic: 1
- infantry_2: 19
  white_rare_mythic: 1
- powerstones_1: 19
  blue_rare_mythic: 1
- etc.
sheets:
  infantry_1:
    exact: true
    deck: "jmp/Infantry 1"
    count: 19
  white_rare_mythic:
    filter: "e:bro c:w"
    use: rare_mythic
```

Things are not set for this on so many levels, before we even get to the issue of foils.
