### ISSUE TITLE
`count` booster key does not work with `use` or `any` 

### ISSUE THREAD

**Issue by axxroytovu** [taw/magic-search-engine#335]
Input:

```yaml
sheets:
  test:
    filter: "e:dsk"
    use: rare_mythic
    count: 10
  test2:
    any:
    - rawquery: "e:dsk r:m"
      rate: 1
    - rawquery: "e:dsk r:r"
      rate: 2
    count: 10
```

Expected behavior:
`Expected {something?} to return 10 got 70`
`Expected {something?} to return 10 got 70`

Current behavior:
No error
